# version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8386:80"
    restart: always

  admin:
    build: ./admin
    ports:
      - "8387:80"
    restart: always
